version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: 484907498501.dkr.ecr.eu-central-1.amazonaws.com/portfolio_app:v02
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      init_volumes:
        condition: service_completed_successfully
    user: "0"

  init_volumes:
    image: alpine
    command: sh -c "mkdir -p /vol/static /vol/media && chown -R 1000:1000 /vol/static /vol/media && chmod -R 775 /vol/static /vol/media"
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
    restart: "no"

  proxy:
    build:
      context: ./proxy
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/vol/static:ro
      - media_volume:/vol/media:ro
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
