version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio:v01
    container_name: portfolio_web
    command: sh -c "/scripts/entrypoint.sh"
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    

  db:
    image: postgres:15
    container_name: portfolio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
  static_volume:
  media_volume:
