# Generated by Django 4.2.16 on 2025-02-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0008_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, default='logos/default-logo.png', null=True, upload_to='clients/'),
        ),
    ]
